language: node_js
node_js:
- 6.10.3
before_script:
- npm run build
deploy:
  email: vladimirmorulus@gamil.com
  provider: npm
  skip_cleanup: true
  before_script: npm run prepublish
  on:
    tags: true
